config:
  use_colors: true
  send_anonymous_usage_stats: false

donorlab_dbt_dataeng:
  target: "{{ env_var('DBT_ENV_SNOWFLAKE_ACCOUNT_ID') }}"
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_ENV_SNOWFLAKE_USER_DEV') }}"

      authenticator: username_password_mfa

      user: "{{ env_var('DBT_ENV_SNOWFLAKE_USER_DEV') }}"
      password: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_PASSWORD_DEV') }}"

      role: "{{ env_var('DBT_ENV_SNOWFLAKE_ROLE_DEV') }}"
      database: "{{ env_var('DBT_ENV_SNOWFLAKE_DATABSE_DEV') }}"
      warehouse: "{{ env_var('DBT_ENV_SNOWFLAKE_WAREHOUSE_DEV') }}"
      schema: "{{ env_var('DBT_ENV_SNOWFLAKE_SCHEMA_DEV') }}"
      threads: 1
      client_session_keep_alive: false

    ci:
      type: snowflake
      account: "{{ env_var('DBT_ENV_SNOWFLAKE_USER_DEV') }}"

      user: "{{ env_var('DBT_ENV_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_PASSWORD') }}"

      role: "{{ env_var('DBT_ENV_SNOWFLAKE_ROLE_CI') }}"
      database: "{{ env_var('DBT_ENV_SNOWFLAKE_DATABSE_CI') }}"
      warehouse: "{{ env_var('DBT_ENV_SNOWFLAKE_WAREHOUSE_CI') }}"
      schema: "DBT_CI_PR_{{ env_var('DBT_ENV_PR_NUM') }}"
      threads: 4
      client_session_keep_alive: false

    prod:
      type: snowflake
      account: "{{ env_var('DBT_ENV_SNOWFLAKE_ACCOUNT_ID') }}"

      user: "{{ env_var('DBT_ENV_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_PASSWORD') }}"

      role: "{{ env_var('DBT_ENV_SNOWFLAKE_ROLE_PROD') }}"
      database: "{{ env_var('DBT_ENV_SNOWFLAKE_DATABSE_PROD') }}"
      warehouse: "{{ env_var('DBT_ENV_SNOWFLAKE_WAREHOUSE_PROD') }}"
      schema: "{{ env_var('DBT_ENV_SNOWFLAKE_SCHEMA_PROD') }}"
      threads: 4
      client_session_keep_alive: false
